create table balance_statement
(
  stock_id varchar(25) not null,
  release_time datetime not null,
  institution_type varchar(40) not null,
  bs_0001 double,
  bs_0002 double,
  bs_0003 double,
  bs_0004 double,
  bs_0005 double,
  bs_0006 double,
  bs_0007 double,
  bs_0008 double,
  bs_0009 double,
  bs_0010 double,
  bs_0011 double,
  bs_0012 double,
  bs_0013 double,
  bs_0014 double,
  bs_0015 double,
  bs_0016 double,
  bs_0017 double,
  bs_0018 double,
  bs_0019 double,
  bs_0020 double,
  bs_0021 double,
  bs_0022 double,
  bs_0023 double,
  bs_0024 double,
  bs_0025 double,
  bs_0026 double,
  bs_0027 double,
  bs_0028 double,
  bs_0029 double,
  bs_0030 double,
  bs_0031 double,
  bs_0032 double,
  bs_0033 double,
  bs_0034 double,
  bs_0035 double,
  bs_0036 double,
  bs_0037 double,
  bs_0038 double,
  bs_0039 double,
  bs_0040 double,
  bs_0041 double,
  bs_0042 double,
  bs_0043 double,
  bs_0044 double,
  bs_0045 double,
  bs_0046 double,
  bs_0047 double,
  bs_0048 double,
  bs_0049 double,
  bs_0050 double,
  bs_0051 double,
  bs_0052 double,
  bs_0053 double,
  bs_0054 double,
  bs_0055 double,
  bs_0056 double,
  bs_0057 double,
  bs_0058 double,
  bs_0059 double,
  bs_0060 double,
  bs_0061 double,
  bs_0062 double,
  bs_0063 double,
  bs_0064 double,
  bs_0065 double,
  bs_0066 double,
  bs_0067 double,
  bs_0068 double,
  bs_0069 double,
  bs_0070 double,
  bs_0071 double,
  bs_0072 double,
  bs_0073 double,
  bs_0074 double,
  bs_0075 double,
  bs_0076 double,
  bs_0077 double,
  bs_0078 double,
  bs_0079 double,
  bs_0080 double,
  bs_0081 double,
  bs_0082 double,
  bs_0083 double,
  bs_0084 double,
  bs_0085 double,
  bs_0086 double,
  bs_0087 double,
  bs_0088 double,
  bs_0089 double,
  bs_0090 double,
  bs_0091 double,
  bs_0092 double,
  bs_0093 double,
  bs_0094 double,
  bs_0095 double,
  bs_0096 double,
  bs_0097 double,
  bs_0098 double,
  bs_0099 double,
  bs_0100 double,
  bs_0101 double,
  bs_0102 double,
  bs_0103 double,
  bs_0104 double,
  bs_0105 double,
  bs_0106 double,
  bs_0107 double,
  bs_0108 double,
  bs_0109 double,
  bs_0110 double,
  bs_0111 double,
  bs_0112 double,
  bs_0113 double,
  bs_0114 double,
  bs_0115 double,
  bs_0116 double,
  bs_0117 double,
  bs_0118 double,
  bs_0119 double,
  bs_0120 double,
  bs_0121 double,
  bs_0122 double,
  bs_0123 double,
  bs_0124 double,
  bs_0125 double,
  bs_0126 double,
  bs_0127 double,
  bs_0128 double,
  bs_0129 double,
  bs_0130 double,
  bs_0131 double,
  bs_0132 double,
  bs_0133 double,
  bs_0134 double,
  bs_0135 double,
  bs_0136 double,
  bs_0137 double,
  bs_0138 double,
  bs_0139 double,
  bs_0140 double,
  bs_0141 double,
  bs_0142 double,
  bs_0143 double,
  bs_0144 double,
  bs_0145 double,
  bs_0146 double,
  bs_0147 double,
  bs_0148 double,
  bs_0149 double,
  bs_0150 double
);
alter table balance_statement
add constraint balance_statement_pk primary key (stock_id, release_time);

create table income_statement
(
  stock_id varchar(25) not null,
  release_time datetime not null,
  institution_type varchar(40) not null,
  is_0001 double,
  is_0002 double,
  is_0003 double,
  is_0004 double,
  is_0005 double,
  is_0006 double,
  is_0007 double,
  is_0008 double,
  is_0009 double,
  is_0010 double,
  is_0011 double,
  is_0012 double,
  is_0013 double,
  is_0014 double,
  is_0015 double,
  is_0016 double,
  is_0017 double,
  is_0018 double,
  is_0019 double,
  is_0020 double,
  is_0021 double,
  is_0022 double,
  is_0023 double,
  is_0024 double,
  is_0025 double,
  is_0026 double,
  is_0027 double,
  is_0028 double,
  is_0029 double,
  is_0030 double,
  is_0031 double,
  is_0032 double,
  is_0033 double,
  is_0034 double,
  is_0035 double,
  is_0036 double,
  is_0037 double,
  is_0038 double,
  is_0039 double,
  is_0040 double,
  is_0041 double,
  is_0042 double,
  is_0043 double,
  is_0044 double,
  is_0045 double,
  is_0046 double,
  is_0047 double,
  is_0048 double,
  is_0049 double,
  is_0050 double,
  is_0051 double,
  is_0052 double,
  is_0053 double,
  is_0054 double,
  is_0055 double,
  is_0056 double,
  is_0057 double,
  is_0058 double,
  is_0059 double,
  is_0060 double,
  is_0061 double,
  is_0062 double,
  is_0063 double,
  is_0064 double,
  is_0065 double,
  is_0066 double,
  is_0067 double,
  is_0068 double,
  is_0069 double,
  is_0070 double,
  is_0071 double,
  is_0072 double,
  is_0073 double,
  is_0074 double,
  is_0075 double,
  is_0076 double,
  is_0077 double,
  is_0078 double,
  is_0079 double,
  is_0080 double,
  is_0081 double,
  is_0082 double,
  is_0083 double,
  is_0084 double,
  is_0085 double,
  is_0086 double,
  is_0087 double,
  is_0088 double,
  is_0089 double,
  is_0090 double,
  is_0091 double,
  is_0092 double,
  is_0093 double,
  is_0094 double,
  is_0095 double,
  is_0096 double,
  is_0097 double,
  is_0098 double,
  is_0099 double,
  is_0100 double,
  is_0101 double,
  is_0102 double,
  is_0103 double,
  is_0104 double,
  is_0105 double,
  is_0106 double,
  is_0107 double,
  is_0108 double,
  is_0109 double,
  is_0110 double,
  is_0111 double,
  is_0112 double,
  is_0113 double,
  is_0114 double,
  is_0115 double,
  is_0116 double,
  is_0117 double,
  is_0118 double,
  is_0119 double,
  is_0120 double,
  is_0121 double,
  is_0122 double,
  is_0123 double,
  is_0124 double,
  is_0125 double,
  is_0126 double,
  is_0127 double,
  is_0128 double,
  is_0129 double,
  is_0130 double,
  is_0131 double,
  is_0132 double,
  is_0133 double,
  is_0134 double,
  is_0135 double,
  is_0136 double,
  is_0137 double,
  is_0138 double,
  is_0139 double,
  is_0140 double,
  is_0141 double,
  is_0142 double,
  is_0143 double,
  is_0144 double,
  is_0145 double,
  is_0146 double,
  is_0147 double,
  is_0148 double,
  is_0149 double,
  is_0150 double
);

alter table income_statement
add constraint income_statement_pk primary key (stock_id, release_time);

create table cash_statement
(
  stock_id varchar(25) not null,
  release_time datetime not null,
  institution_type varchar(40) not null,
  cs_0001 double,
  cs_0002 double,
  cs_0003 double,
  cs_0004 double,
  cs_0005 double,
  cs_0006 double,
  cs_0007 double,
  cs_0008 double,
  cs_0009 double,
  cs_0010 double,
  cs_0011 double,
  cs_0012 double,
  cs_0013 double,
  cs_0014 double,
  cs_0015 double,
  cs_0016 double,
  cs_0017 double,
  cs_0018 double,
  cs_0019 double,
  cs_0020 double,
  cs_0021 double,
  cs_0022 double,
  cs_0023 double,
  cs_0024 double,
  cs_0025 double,
  cs_0026 double,
  cs_0027 double,
  cs_0028 double,
  cs_0029 double,
  cs_0030 double,
  cs_0031 double,
  cs_0032 double,
  cs_0033 double,
  cs_0034 double,
  cs_0035 double,
  cs_0036 double,
  cs_0037 double,
  cs_0038 double,
  cs_0039 double,
  cs_0040 double,
  cs_0041 double,
  cs_0042 double,
  cs_0043 double,
  cs_0044 double,
  cs_0045 double,
  cs_0046 double,
  cs_0047 double,
  cs_0048 double,
  cs_0049 double,
  cs_0050 double,
  cs_0051 double,
  cs_0052 double,
  cs_0053 double,
  cs_0054 double,
  cs_0055 double,
  cs_0056 double,
  cs_0057 double,
  cs_0058 double,
  cs_0059 double,
  cs_0060 double,
  cs_0061 double,
  cs_0062 double,
  cs_0063 double,
  cs_0064 double,
  cs_0065 double,
  cs_0066 double,
  cs_0067 double,
  cs_0068 double,
  cs_0069 double,
  cs_0070 double,
  cs_0071 double,
  cs_0072 double,
  cs_0073 double,
  cs_0074 double,
  cs_0075 double,
  cs_0076 double,
  cs_0077 double,
  cs_0078 double,
  cs_0079 double,
  cs_0080 double,
  cs_0081 double,
  cs_0082 double,
  cs_0083 double,
  cs_0084 double,
  cs_0085 double,
  cs_0086 double,
  cs_0087 double,
  cs_0088 double,
  cs_0089 double,
  cs_0090 double,
  cs_0091 double,
  cs_0092 double,
  cs_0093 double,
  cs_0094 double,
  cs_0095 double,
  cs_0096 double,
  cs_0097 double,
  cs_0098 double,
  cs_0099 double,
  cs_0100 double,
  cs_0101 double,
  cs_0102 double,
  cs_0103 double,
  cs_0104 double,
  cs_0105 double,
  cs_0106 double,
  cs_0107 double,
  cs_0108 double,
  cs_0109 double,
  cs_0110 double,
  cs_0111 double,
  cs_0112 double,
  cs_0113 double,
  cs_0114 double,
  cs_0115 double,
  cs_0116 double,
  cs_0117 double,
  cs_0118 double,
  cs_0119 double,
  cs_0120 double,
  cs_0121 double,
  cs_0122 double,
  cs_0123 double,
  cs_0124 double,
  cs_0125 double,
  cs_0126 double,
  cs_0127 double,
  cs_0128 double,
  cs_0129 double,
  cs_0130 double,
  cs_0131 double,
  cs_0132 double,
  cs_0133 double,
  cs_0134 double,
  cs_0135 double,
  cs_0136 double,
  cs_0137 double,
  cs_0138 double,
  cs_0139 double,
  cs_0140 double,
  cs_0141 double,
  cs_0142 double,
  cs_0143 double,
  cs_0144 double,
  cs_0145 double,
  cs_0146 double,
  cs_0147 double,
  cs_0148 double,
  cs_0149 double,
  cs_0150 double
);

alter table cash_statement
add constraint cash_statement_pk primary key (stock_id, release_time);

create table fin_lookup_ml
(column_name  varchar(31) not null,
 table_name   varchar(31) not null,
 category     varchar(100),
 chinese_name varchar(100),
 english_name varchar(100));
ENGINE=InnoDB DEFAULT CHARSET=gbk;

alter table fin_lookup_ml
add constraint fin_lookup_ml primary key (column_name, table_name);

insert into fin_lookup_ml (column_name, table_name, category, chinese_name,english_name) 
values('bs_0001', 'balance_statement', 'Current Asset', '货币资金(万元)', ''),
('bs_0002', 'balance_statement', 'Current Asset', '结算备付金(万元)', ''),
('bs_0003', 'balance_statement', 'Current Asset', '拆出资金(万元)', ''),
('bs_0004', 'balance_statement', 'Current Asset', '交易性金融资产(万元)', ''),
('bs_0005', 'balance_statement', 'Current Asset', '衍生金融资产(万元)', ''),
('bs_0006', 'balance_statement', 'Current Asset', '应收票据(万元)', ''),
('bs_0007', 'balance_statement', 'Current Asset', '应收账款(万元)', ''),
('bs_0008', 'balance_statement', 'Current Asset', '预付款项(万元)', ''),
('bs_0009', 'balance_statement', 'Current Asset', '应收保费(万元)', ''),
('bs_0010', 'balance_statement', 'Current Asset', '应收分保账款(万元)', ''),
('bs_0011', 'balance_statement', 'Current Asset', '应收分保合同准备金(万元)', ''),
('bs_0012', 'balance_statement', 'Current Asset', '应收利息(万元)', ''),
('bs_0013', 'balance_statement', 'Current Asset', '应收股利(万元)', ''),
('bs_0014', 'balance_statement', 'Current Asset', '其他应收款(万元)', ''),
('bs_0015', 'balance_statement', 'Current Asset', '应收出口退税(万元)', ''),
('bs_0016', 'balance_statement', 'Current Asset', '应收补贴款(万元)', ''),
('bs_0017', 'balance_statement', 'Current Asset', '应收保证金(万元)', ''),
('bs_0018', 'balance_statement', 'Current Asset', '内部应收款(万元)', ''),
('bs_0019', 'balance_statement', 'Current Asset', '买入返售金融资产(万元)', ''),
('bs_0020', 'balance_statement', 'Current Asset', '存货(万元)', ''),
('bs_0021', 'balance_statement', 'Current Asset', '待摊费用(万元)', ''),
('bs_0022', 'balance_statement', 'Current Asset', '待处理流动资产损益(万元)', ''),
('bs_0023', 'balance_statement', 'Current Asset', '一年内到期的非流动资产(万元)', ''),
('bs_0024', 'balance_statement', 'Current Asset', '其他流动资产(万元)', ''),
('bs_0025', 'balance_statement', 'Current Asset Summary', '流动资产合计(万元)', ''),
('bs_0026', 'balance_statement', 'Fixed Assets', '发放贷款及垫款(万元)', ''),
('bs_0027', 'balance_statement', 'Fixed Assets', '可供出售金融资产(万元)', ''),
('bs_0028', 'balance_statement', 'Fixed Assets', '持有至到期投资(万元)', ''),
('bs_0029', 'balance_statement', 'Fixed Assets', '长期应收款(万元)', ''),
('bs_0030', 'balance_statement', 'Fixed Assets', '长期股权投资(万元)', ''),
('bs_0031', 'balance_statement', 'Fixed Assets', '其他长期投资(万元)', ''),
('bs_0032', 'balance_statement', 'Fixed Assets', '投资性房地产(万元)', ''),
('bs_0033', 'balance_statement', 'Fixed Assets', '固定资产原值(万元)', ''),
('bs_0034', 'balance_statement', 'Fixed Assets', '累计折旧(万元)', ''),
('bs_0035', 'balance_statement', 'Fixed Assets', '固定资产净值(万元)', ''),
('bs_0036', 'balance_statement', 'Fixed Assets', '固定资产减值准备(万元)', ''),
('bs_0037', 'balance_statement', 'Fixed Assets', '固定资产(万元)', ''),
('bs_0038', 'balance_statement', 'Fixed Assets', '在建工程(万元)', ''),
('bs_0039', 'balance_statement', 'Fixed Assets', '工程物资(万元)', ''),
('bs_0040', 'balance_statement', 'Fixed Assets', '固定资产清理(万元)', ''),
('bs_0041', 'balance_statement', 'Fixed Assets', '生产性生物资产(万元)', ''),
('bs_0042', 'balance_statement', 'Fixed Assets', '公益性生物资产(万元)', ''),
('bs_0043', 'balance_statement', 'Fixed Assets', '油气资产(万元)', ''),
('bs_0044', 'balance_statement', 'Fixed Assets', '无形资产(万元)', ''),
('bs_0045', 'balance_statement', 'Fixed Assets', '开发支出(万元)', ''),
('bs_0046', 'balance_statement', 'Fixed Assets', '商誉(万元)', ''),
('bs_0047', 'balance_statement', 'Fixed Assets', '长期待摊费用(万元)', ''),
('bs_0048', 'balance_statement', 'Fixed Assets', '股权分置流通权(万元)', ''),
('bs_0049', 'balance_statement', 'Fixed Assets', '递延所得税资产(万元)', ''),
('bs_0050', 'balance_statement', 'Fixed Assets', '其他非流动资产(万元)', ''),
('bs_0051', 'balance_statement', 'Fixed Assets Summary', '非流动资产合计(万元)', ''),
('bs_0052', 'balance_statement', 'Assets Summary', '资产总计(万元)', ''),
('bs_0053', 'balance_statement', 'Current Liabilities', '短期借款(万元)', ''),
('bs_0054', 'balance_statement', 'Current Liabilities', '向中央银行借款(万元)', ''),
('bs_0055', 'balance_statement', 'Current Liabilities', '吸收存款及同业存放(万元)', ''),
('bs_0056', 'balance_statement', 'Current Liabilities', '拆入资金(万元)', ''),
('bs_0057', 'balance_statement', 'Current Liabilities', '交易性金融负债(万元)', ''),
('bs_0058', 'balance_statement', 'Current Liabilities', '衍生金融负债(万元)', ''),
('bs_0059', 'balance_statement', 'Current Liabilities', '应付票据(万元)', ''),
('bs_0060', 'balance_statement', 'Current Liabilities', '应付账款(万元)', ''),
('bs_0061', 'balance_statement', 'Current Liabilities', '预收账款(万元)', ''),
('bs_0062', 'balance_statement', 'Current Liabilities', '卖出回购金融资产款(万元)', ''),
('bs_0063', 'balance_statement', 'Current Liabilities', '应付手续费及佣金(万元)', ''),
('bs_0064', 'balance_statement', 'Current Liabilities', '应付职工薪酬(万元)', ''),
('bs_0065', 'balance_statement', 'Current Liabilities', '应交税费(万元)', ''),
('bs_0066', 'balance_statement', 'Current Liabilities', '应付利息(万元)', ''),
('bs_0067', 'balance_statement', 'Current Liabilities', '应付股利(万元)', ''),
('bs_0068', 'balance_statement', 'Current Liabilities', '其他应交款(万元)', ''),
('bs_0069', 'balance_statement', 'Current Liabilities', '应付保证金(万元)', ''),
('bs_0070', 'balance_statement', 'Current Liabilities', '内部应付款(万元)', ''),
('bs_0071', 'balance_statement', 'Current Liabilities', '其他应付款(万元)', ''),
('bs_0072', 'balance_statement', 'Current Liabilities', '预提费用(万元)', ''),
('bs_0073', 'balance_statement', 'Current Liabilities', '预计流动负债(万元)', ''),
('bs_0074', 'balance_statement', 'Current Liabilities', '应付分保账款(万元)', ''),
('bs_0075', 'balance_statement', 'Current Liabilities', '保险合同准备金(万元)', ''),
('bs_0076', 'balance_statement', 'Current Liabilities', '代理买卖证券款(万元)', ''),
('bs_0077', 'balance_statement', 'Current Liabilities', '代理承销证券款(万元)', ''),
('bs_0078', 'balance_statement', 'Current Liabilities', '国际票证结算(万元)', ''),
('bs_0079', 'balance_statement', 'Current Liabilities', '国内票证结算(万元)', ''),
('bs_0080', 'balance_statement', 'Current Liabilities', '递延收益(万元)', ''),
('bs_0081', 'balance_statement', 'Current Liabilities', '应付短期债券(万元)', ''),
('bs_0082', 'balance_statement', 'Current Liabilities', '一年内到期的非流动负债(万元)', ''),
('bs_0083', 'balance_statement', 'Current Liabilities', '其他流动负债(万元)', ''),
('bs_0084', 'balance_statement', 'Current Liabilities Summary', '流动负债合计(万元)', ''),
('bs_0085', 'balance_statement', 'Non-current Liabilities', '长期借款(万元)', ''),
('bs_0086', 'balance_statement', 'Non-current Liabilities', '应付债券(万元)', ''),
('bs_0087', 'balance_statement', 'Non-current Liabilities', '长期应付款(万元)', ''),
('bs_0088', 'balance_statement', 'Non-current Liabilities', '专项应付款(万元)', ''),
('bs_0089', 'balance_statement', 'Non-current Liabilities', '预计非流动负债(万元)', ''),
('bs_0090', 'balance_statement', 'Non-current Liabilities', '长期递延收益(万元)', ''),
('bs_0091', 'balance_statement', 'Non-current Liabilities', '递延所得税负债(万元)', ''),
('bs_0092', 'balance_statement', 'Non-current Liabilities', '其他非流动负债(万元)', ''),
('bs_0093', 'balance_statement', 'Non-current Liabilities Summary', '非流动负债合计(万元)', ''),
('bs_0094', 'balance_statement', 'Liabilities Summary', '负债合计(万元)', ''),
('bs_0095', 'balance_statement', 'Shareholder Equity', '实收资本(或股本)(万元)', ''),
('bs_0096', 'balance_statement', 'Shareholder Equity', '资本公积(万元)', ''),
('bs_0097', 'balance_statement', 'Shareholder Equity', '减:库存股(万元)', ''),
('bs_0098', 'balance_statement', 'Shareholder Equity', '专项储备(万元)', ''),
('bs_0099', 'balance_statement', 'Shareholder Equity', '盈余公积(万元)', ''),
('bs_0100', 'balance_statement', 'Shareholder Equity', '一般风险准备(万元)', ''),
('bs_0101', 'balance_statement', 'Shareholder Equity', '未确定的投资损失(万元)', ''),
('bs_0102', 'balance_statement', 'Shareholder Equity', '未分配利润(万元)', ''),
('bs_0103', 'balance_statement', 'Shareholder Equity', '拟分配现金股利(万元)', ''),
('bs_0104', 'balance_statement', 'Shareholder Equity', '外币报表折算差额(万元)', ''),
('bs_0105', 'balance_statement', 'Shareholder Equity', '归属于母公司股东权益合计(万元)', ''),
('bs_0106', 'balance_statement', 'Shareholder Equity', '少数股东权益(万元)', ''),
('bs_0107', 'balance_statement', 'Shareholder Equity Summary', '所有者权益(或股东权益)合计(万元)', ''),
('bs_0108', 'balance_statement', 'Liabilities and Equity Summary', '负债和所有者权益(或股东权益)总计(万元)', ''),
('is_0001', 'income_statement', 'Revenue Summary', '营业总收入(万元)', ''),
('is_0002', 'income_statement', 'Revenue', '营业收入(万元)', ''),
('is_0003', 'income_statement', 'Revenue', '利息收入(万元)', ''),
('is_0004', 'income_statement', 'Revenue', '已赚保费(万元)', ''),
('is_0005', 'income_statement', 'Revenue', '手续费及佣金收入(万元)', ''),
('is_0006', 'income_statement', 'Revenue', '房地产销售收入(万元)', ''),
('is_0007', 'income_statement', 'Revenue', '其他业务收入(万元)', ''),
('is_0008', 'income_statement', 'Expense Summary', '营业总成本(万元)', ''),
('is_0009', 'income_statement', 'Expense', '营业成本(万元)', ''),
('is_0010', 'income_statement', 'Expense', '利息支出(万元)', ''),
('is_0011', 'income_statement', 'Expense', '手续费及佣金支出(万元)', ''),
('is_0012', 'income_statement', 'Expense', '房地产销售成本(万元)', ''),
('is_0013', 'income_statement', 'Expense', '研发费用(万元)', ''),
('is_0014', 'income_statement', 'Expense', '退保金(万元)', ''),
('is_0015', 'income_statement', 'Expense', '赔付支出净额(万元)', ''),
('is_0016', 'income_statement', 'Expense', '提取保险合同准备金净额(万元)', ''),
('is_0017', 'income_statement', 'Expense', '保单红利支出(万元)', ''),
('is_0018', 'income_statement', 'Expense', '分保费用(万元)', ''),
('is_0019', 'income_statement', 'Expense', '其他业务成本(万元)', ''),
('is_0020', 'income_statement', 'Expense', '营业税金及附加(万元)', ''),
('is_0021', 'income_statement', 'Expense', '销售费用(万元)', ''),
('is_0022', 'income_statement', 'Expense', '管理费用(万元)', ''),
('is_0023', 'income_statement', 'Expense', '财务费用(万元)', ''),
('is_0024', 'income_statement', 'Expense', '资产减值损失(万元)', ''),
('is_0025', 'income_statement', 'Expense', '公允价值变动收益(万元)', ''),
('is_0026', 'income_statement', 'Expense', '投资收益(万元)', ''),
('is_0027', 'income_statement', 'Expense', '对联营企业和合营企业的投资收益(万元)', ''),
('is_0028', 'income_statement', 'Expense', '汇兑收益(万元)', ''),
('is_0029', 'income_statement', 'Expense', '期货损益(万元)', ''),
('is_0030', 'income_statement', 'Expense', '托管收益(万元)', ''),
('is_0031', 'income_statement', 'Expense', '补贴收入(万元)', ''),
('is_0032', 'income_statement', 'Expense', '其他业务利润(万元)', ''),
('is_0033', 'income_statement', 'Operating Profit Summary', '营业利润(万元)', ''),
('is_0034', 'income_statement', 'Operating Profit', '营业外收入(万元)', ''),
('is_0035', 'income_statement', 'Operating Profit', '营业外支出(万元)', ''),
('is_0036', 'income_statement', 'Operating Profit', '非流动资产处置损失(万元)', ''),
('is_0037', 'income_statement', 'Operating Profit', '利润总额(万元)', ''),
('is_0038', 'income_statement', 'Operating Profit', '所得税费用(万元)', ''),
('is_0039', 'income_statement', 'Operating Profit', '未确认投资损失(万元)', ''),
('is_0040', 'income_statement', 'Net Profit Summary', '净利润(万元)', ''),
('is_0041', 'income_statement', 'Net Profit', '归属于母公司所有者的净利润(万元)', ''),
('is_0042', 'income_statement', 'Net Profit', '被合并方在合并前实现净利润(万元)', ''),
('is_0043', 'income_statement', 'Net Profit', '少数股东损益(万元)', ''),
('is_0044', 'income_statement', 'EPS', '基本每股收益', ''),
('is_0045', 'income_statement', 'EPS', '稀释每股收益', ''),
('cs_0001', 'cash_statement', 'Cash Flows from Operating Activities', '销售商品、提供劳务收到的现金(万元)', ''),
('cs_0002', 'cash_statement', 'Cash Flows from Operating Activities', '客户存款和同业存放款项净增加额(万元)', ''),
('cs_0003', 'cash_statement', 'Cash Flows from Operating Activities', '向中央银行借款净增加额(万元', ''),
('cs_0004', 'cash_statement', 'Cash Flows from Operating Activities', '向其他金融机构拆入资金净增加额(万元)', ''),
('cs_0005', 'cash_statement', 'Cash Flows from Operating Activities', '收到原保险合同保费取得的现金(万元)', ''),
('cs_0006', 'cash_statement', 'Cash Flows from Operating Activities', '收到再保险业务现金净额(万元)', ''),
('cs_0007', 'cash_statement', 'Cash Flows from Operating Activities', '保户储金及投资款净增加额(万元)', ''),
('cs_0008', 'cash_statement', 'Cash Flows from Operating Activities', '处置交易性金融资产净增加额(万元)', ''),
('cs_0009', 'cash_statement', 'Cash Flows from Operating Activities', '收取利息、手续费及佣金的现金(万元)', ''),
('cs_0010', 'cash_statement', 'Cash Flows from Operating Activities', '拆入资金净增加额(万元)', ''),
('cs_0011', 'cash_statement', 'Cash Flows from Operating Activities', '回购业务资金净增加额(万元)', ''),
('cs_0012', 'cash_statement', 'Cash Flows from Operating Activities', '收到的税费返还(万元)', ''),
('cs_0013', 'cash_statement', 'Cash Flows from Operating Activities', '收到的其他与经营活动有关的现金(万元)', ''),
('cs_0014', 'cash_statement', 'Cash Flows from Operating Activities', '经营活动现金流入小计(万元)', ''),
('cs_0015', 'cash_statement', 'Cash Flows from Operating Activities', '购买商品、接受劳务支付的现金(万元)', ''),
('cs_0016', 'cash_statement', 'Cash Flows from Operating Activities', '客户贷款及垫款净增加额(万元)', ''),
('cs_0017', 'cash_statement', 'Cash Flows from Operating Activities', '存放中央银行和同业款项净增加额(万元)', ''),
('cs_0018', 'cash_statement', 'Cash Flows from Operating Activities', '支付原保险合同赔付款项的现金(万元)', ''),
('cs_0019', 'cash_statement', 'Cash Flows from Operating Activities', '支付利息、手续费及佣金的现金(万元)', ''),
('cs_0020', 'cash_statement', 'Cash Flows from Operating Activities', '支付保单红利的现金(万元)', ''),
('cs_0021', 'cash_statement', 'Cash Flows from Operating Activities', '支付给职工以及为职工支付的现金(万元)', ''),
('cs_0022', 'cash_statement', 'Cash Flows from Operating Activities', '支付的各项税费(万元)', ''),
('cs_0023', 'cash_statement', 'Cash Flows from Operating Activities', '支付的其他与经营活动有关的现金(万元)', ''),
('cs_0024', 'cash_statement', 'Cash Flows from Operating Activities', '经营活动现金流出小计(万元)', ''),
('cs_0025', 'cash_statement', 'Cash Flows from Operating Activities', '经营活动产生的现金流量净额(万元)', ''),
('cs_0026', 'cash_statement', 'Cash Flow from Investment Activities', '收回投资所收到的现金(万元)', ''),
('cs_0027', 'cash_statement', 'Cash Flow from Investment Activities', '取得投资收益所收到的现金(万元)', ''),
('cs_0028', 'cash_statement', 'Cash Flow from Investment Activities', '处置固定资产、无形资产和其他长期资产所收回的现金净额(万元)', ''),
('cs_0029', 'cash_statement', 'Cash Flow from Investment Activities', '处置子公司及其他营业单位收到的现金净额(万元)', ''),
('cs_0030', 'cash_statement', 'Cash Flow from Investment Activities', '收到的其他与投资活动有关的现金(万元)', ''),
('cs_0031', 'cash_statement', 'Cash Flow from Investment Activities', '减少质押和定期存款所收到的现金(万元)', ''),
('cs_0032', 'cash_statement', 'Cash Flow from Investment Activities', '投资活动现金流入小计(万元)', ''),
('cs_0033', 'cash_statement', 'Cash Flow from Investment Activities', '购建固定资产、无形资产和其他长期资产所支付的现金(万元)', ''),
('cs_0034', 'cash_statement', 'Cash Flow from Investment Activities', '投资所支付的现金(万元)', ''),
('cs_0035', 'cash_statement', 'Cash Flow from Investment Activities', '质押贷款净增加额(万元)', ''),
('cs_0036', 'cash_statement', 'Cash Flow from Investment Activities', '取得子公司及其他营业单位支付的现金净额(万元)', ''),
('cs_0037', 'cash_statement', 'Cash Flow from Investment Activities', '支付的其他与投资活动有关的现金(万元)', ''),
('cs_0038', 'cash_statement', 'Cash Flow from Investment Activities', '增加质押和定期存款所支付的现金(万元)', ''),
('cs_0039', 'cash_statement', 'Cash Flow from Investment Activities', '投资活动现金流出小计(万元)', ''),
('cs_0040', 'cash_statement', 'Cash Flow from Investment Activities', '投资活动产生的现金流量净额(万元)', ''),
('cs_0041', 'cash_statement', 'Cash Flow from Financing Activities', '吸收投资收到的现金(万元)', ''),
('cs_0042', 'cash_statement', 'Cash Flow from Financing Activities', '其中：子公司吸收少数股东投资收到的现金(万元)', ''),
('cs_0043', 'cash_statement', 'Cash Flow from Financing Activities', '取得借款收到的现金(万元)', ''),
('cs_0044', 'cash_statement', 'Cash Flow from Financing Activities', '发行债券收到的现金(万元)', ''),
('cs_0045', 'cash_statement', 'Cash Flow from Financing Activities', '收到其他与筹资活动有关的现金(万元)', ''),
('cs_0046', 'cash_statement', 'Cash Flow from Financing Activities', '筹资活动现金流入小计(万元)', ''),
('cs_0047', 'cash_statement', 'Cash Flow from Financing Activities', '偿还债务支付的现金(万元)', ''),
('cs_0048', 'cash_statement', 'Cash Flow from Financing Activities', '分配股利、利润或偿付利息所支付的现金(万元)', ''),
('cs_0049', 'cash_statement', 'Cash Flow from Financing Activities', '其中：子公司支付给少数股东的股利、利润(万元)', ''),
('cs_0050', 'cash_statement', 'Cash Flow from Financing Activities', '支付其他与筹资活动有关的现金(万元)', ''),
('cs_0051', 'cash_statement', 'Cash Flow from Financing Activities', '筹资活动现金流出小计(万元)', ''),
('cs_0052', 'cash_statement', 'Cash Flow from Financing Activities', '筹资活动产生的现金流量净额(万元)', ''),
('cs_0053', 'cash_statement', 'Effect of Changes in Exchange Rate on Cash and Cash Equivalents', '汇率变动对现金及现金等价物的影响(万元)', ''),
('cs_0054', 'cash_statement', 'Net Increase in Cash and Cash Equivalents Amount', '现金及现金等价物净增加额(万元)', ''),
('cs_0055', 'cash_statement', 'Net Increase in Cash and Cash Equivalents Amount', '加:期初现金及现金等价物余额(万元)', ''),
('cs_0056', 'cash_statement', 'Net Increase in Cash and Cash Equivalents Amount', '期末现金及现金等价物余额(万元)', '');

insert into fin_lookup_ml (column_name, table_name, category, chinese_name,english_name) 
values('cs_0057','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','净利润(万元)',''),
('cs_0058','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','少数股东损益(万元)',''),
('cs_0059','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','未确认的投资损失(万元)',''),
('cs_0060','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','资产减值准备(万元)',''),
('cs_0061','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','固定资产折旧、油气资产折耗、生产性物资折旧(万元)',''),
('cs_0062','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','无形资产摊销(万元)',''),
('cs_0063','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','长期待摊费用摊销(万元)',''),
('cs_0064','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','待摊费用的减少(万元)',''),
('cs_0065','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','预提费用的增加(万元)',''),
('cs_0066','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','处置固定资产、无形资产和其他长期资产的损失(万元)',''),
('cs_0067','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','固定资产报废损失(万元)',''),
('cs_0068','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','公允价值变动损失(万元)',''),
('cs_0069','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','递延收益增加(减：减少)(万元)',''),
('cs_0070','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','预计负债(万元)',''),
('cs_0071','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','财务费用(万元)',''),
('cs_0072','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','投资损失(万元)',''),
('cs_0073','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','递延所得税资产减少(万元)',''),
('cs_0074','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','递延所得税负债增加(万元)',''),
('cs_0075','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','存货的减少(万元)',''),
('cs_0076','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','经营性应收项目的减少(万元)',''),
('cs_0077','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','经营性应付项目的增加(万元)',''),
('cs_0078','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','已完工尚未结算款的减少(减:增加)(万元)',''),
('cs_0079','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','已结算尚未完工款的增加(减:减少)(万元)',''),
('cs_0080','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','其他(万元)',''),
('cs_0081','cash_statement','Reconcilation of Net Income to Operating in Cash Flow','经营活动产生现金流量净额(万元)',''),
('cs_0082','cash_statement','Major Investment and Financing Activities not Involving Cash Receipts and Payments','债务转为资本(万元)',''),
('cs_0083','cash_statement','Major Investment and Financing Activities not Involving Cash Receipts and Payments','一年内到期的可转换公司债券(万元)',''),
('cs_0084','cash_statement','Major Investment and Financing Activities not Involving Cash Receipts and Payments','融资租入固定资产(万元)',''),
('cs_0085','cash_statement','Change of Cash and Cash Equivalents','现金的期末余额(万元)',''),
('cs_0086','cash_statement','Change of Cash and Cash Equivalents','现金的期初余额(万元)',''),
('cs_0087','cash_statement','Change of Cash and Cash Equivalents','现金等价物的期末余额(万元)',''),
('cs_0088','cash_statement','Change of Cash and Cash Equivalents','现金等价物的期初余额(万元)',''),
('cs_0089','cash_statement','Change of Cash and Cash Equivalents','现金及现金等价物的净增加额(万元)','');





alter database financial character set gbk;
alter table fin_lookup_ml  convert to character set gbk;


























